### ISSUE TITLE
Unable to connect to Guest Science Manager 

### ISSUE THREAD

**Issue by elliotwave** [nasa/astrobee_android#1]
I have a problem connecting to GSM when I run gds_simulator.py. I already confirmed that android emulator and Astrobee simulator was running. GSM also seems to run normally in android emulator. I try to restart the GSM but still no luck.  I already make sure that I was able to ping both from adb shell and ubuntu for llp and hlp. The robot can also be controlled from teleop but there seems to be an error after I run Astrobee simulator. Is this what causing the issue to connect to GSM? Any help would be much appreciated. Thank you

![Screenshot from 2020-02-14 22-53-57](https://user-images.githubusercontent.com/47345317/74546372-12044f00-4f7d-11ea-84d9-903ab41f945d.png)

**Comment by kbrowne15** [comment]
@elliotwave Were you able to solve this issue? Sorry for the very late response.

**Comment by kbrowne15** [comment]
Older issue. If this is still an issue, please open a new issue.
