### ISSUE TITLE
Look into why the sci cam wasn't able to recover

### ISSUE THREAD

**Issue by kbrowne15** [nasa/astrobee_android#23]
During the Soundsee data 3 activity, the sci cam stopped working after roughly 50 images. The apk was able to detect it but unable to recover. Usually a take picture or restart continuous picture taking fixes this but during the activity, the camera returned an error saying the camera was busy. Need to look into this and try to run the scicam during the next CM.

**Comment by oleg-alexandrov** [comment]
A quirk of the android camera is that if some buffer or other resources are not freed up after each shot, it will eventually start complaining.  It is a wild guess if this is what is causes the issues, and most likely not. 

It may still be worth to look at the logic around the time the picture is taken and see if all proper cleanup takes place, given that the camera starts complaining after a while. It would also be interesting to see if the memory usage goes up after each shot and does not go back down.

Funny that Java is garbage-collected, but one still need to watch over such things.
