### ISSUE TITLE
Fix the Astrobee API file generation scripts

### ISSUE THREAD

**Issue by kbrowne15** [nasa/astrobee_android#3]
The Astrobee API file generation scripts use files from Astrobee common. The common repo has been integrated into the Astrobee  repo so these scripts need to be updated to the newest file locations.

**Comment by bcoltin** [comment]
Not going to do this.

**Comment by kbrowne15** [comment]
Actually, this was done in pr https://github.com/nasa/astrobee_android/pull/4. I probably just forgot to close it.
