### ISSUE TITLE
Buliding the Astrobee API with Ubuntu 20.04

### ISSUE THREAD

**Issue by SenorGentleHands** [nasa/astrobee_android#44]
The Astrobee ROS [instructions](https://nasa.github.io/astrobee/v/develop/md_INSTALL.html#autotoc_md8) for building the ROS packages recommend Ubuntu 20.04. However, the Astrobee Android API build [instructions](https://github.com/nasa/astrobee_android/blob/master/astrobee_api/readme.md) indicate that users need to install `ros-kinetic-rosjava` in order to build the `ff_msgs` jar, which cannot be installed properly on Ubuntu 20.04 (or possibly 18.04).

When using Ubuntu 20.04 I can only install ROS Noetic, so I tried to install `ros-kinetic-rosjava` from source from [this repo](https://raw.githubusercontent.com/rosjava/rosjava/kinetic/rosjava.rosinstall) found using the ROS Wiki [Source Installation Instructions](http://wiki.ros.org/rosjava/Tutorials/kinetic/Source%20Installation). When I try to build `ff_msgs` using the command `make ff_msgs_generate_messages_java_gradle`, I get the following output:

`ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies:`
`rosjava_messages: Cannot locate rosdep definition for [world_canvas_msgs]`
`genjava: No definition of [python-catkin-pkg] for OS version [focal]`

The error output indicates that the issue is caused by dependencies that have changed between the two ROS versions. The Astrobee ROS instructions indicate that the robot hardware on ISS currently runs Ubuntu 16.04, which is supported by ROS Kinetic. I am currently trying Ubuntu 16.04 to see if that works.

**Comment by rgarciaruiz** [comment]
Our approach to addressing this issue with other users so far has been to provide/generate the necessary JAR files (built with Ubuntu 16) and use kinetic on Android while keeping the simulator on Ubuntu 20 (noetic).

Of course, this might not work for all use cases (and it's inconvenient) so we are looking into other options as well.

Documentation is lagging behind but we are working on it, so we appreciate your feedback.

**Comment by marinagmoreira** [comment]
I would add that we have an example on how to generate these jar files with docker on Ubuntu 20.04 in https://github.com/nasa/isaac/blob/master/scripts/docker/build_apk.Dockerfile and it is part of the isaac CI in https://github.com/nasa/isaac/blob/master/.github/workflows/apk.yaml (meaning it runs every time someone does a commit).

I would also point out that in 18.04 I only built the jars and the apk compiled natively, but in 20.04 I had to put the entire flow inside the Docker image. (https://github.com/nasa/isaac/blob/v0.2.5/scripts/docker/build_msgs_jar.Dockerfile and https://github.com/nasa/isaac/blob/v0.2.5/.github/workflows/apk.yaml)

**Comment by bcoltin** [comment]
We believe Ruben fixed this.
