### ISSUE TITLE
Building the Astrobee API with Android Studio fails because of maven dependency

### ISSUE THREAD

**Issue by erobinson-mei** [nasa/astrobee_android#45]
The `espresso-core:2.0.2` dependency in the `build.gradle` for the `astrobee_android/guest_science`  project needs to be changed to `espresso-core:2.2.2` because the maven repository doesn't host 2.0.2 anymore.

```java

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    compile 'com.android.support:appcompat-v7:26.+'
    testCompile 'junit:junit:4.12'
}
```

**Comment by marinagmoreira** [comment]
I'm a bit confused, you say it needs to be changed to 2.2.2, but if I search the repo, it's already 2.2.2:
https://github.com/search?q=repo%3Anasa%2Fastrobee_android%20androidTestCompile(%27com.android.support.test.espresso%3Aespresso-core%3A&type=code

**Comment by erobinson-mei** [comment]
I can see it on the latest commit. I am not sure how this dependency changed for me.
