### ISSUE TITLE
Android Studio Logcat with Guest Science App

### ISSUE THREAD

**Issue by erobinson-mei** [nasa/astrobee_android#50]
I am developing an guest science application and need the position of the Astrobee. I can't tell if I am receiving the coordinates and I cannot get log output to show up in Logcat. Is it recommended to log to files or is Logcat working for other developers? The log output shows up if I launch with `adb`, but I think `factory.getRobot()` fails when the app isn't launched with the guest science manager.

**Comment by erobinson-mei** [comment]
I was able to figure out how acquire position coordinates. I didn't need the guest science manager, I just didn't have the IP addresses set up correctly.

I am still having issues viewing logs via Logcat with apps launched from the guest science manager.

**Comment by rgarciaruiz** [comment]
Using the application ID (defined in build.gradle) of your apk you can get the logcat based on the PID:

1. Find the PID: adb shell pidof your.package.id
3. Logcat based on that: adb logcat --pid=<PID>

You can combine those commands, of course, to make a one-liner, and/or you can check if the PID exists first.

I hope this helps.

**Comment by rgarciaruiz** [comment]
Were you able to make this work? Does this solve your issue?

**Comment by erobinson-mei** [comment]
Yes, I finally got around to trying it. I am developing both the Android app and payload software so I am sorry for the delay. This will help a ton.
