### ISSUE TITLE
Communicating with Payloads

### ISSUE THREAD

**Issue by erobinson-mei** [nasa/astrobee_android#53]
I have an HLP development board and a prototype payload connected via USB. To establish communications I had to assign an IP address to the USB port on the HLP using `adb`. Is there already a static IP defined for the USB ports, or should I provide the IP addresses I used in my documentation?

**Comment by rgarciaruiz** [comment]
If I understand correctly, you have an Ethernet to USB adapter connecting your payload to the HLP board. Therefore, when running `adb shell ifconfig` it shows as an additional network interface.

If this is correct, then yes, an IP needs to be assigned. In the robots, this is taken care of by a script always running in the HLP that detects when a new interface shows up and assigns a pre-defined IP, plus some additional configuration.

For initial testing, any IP that works is okay, but for testing in the lab or in the ISS, you will need to follow our predefined network configuration. 

If you are interested in knowing more about this please contact me at ruben.m.garciaruiz@nasa.gov

**Comment by erobinson-mei** [comment]
I think it would be best to follow the predefined network configuration. However, I need to hold on this for now. I will close this out as an issue.
